### ISSUE TITLE
Doesn't take tab width into account

### ISSUE THREAD

**Issue by emichael** [abrookins/WrapToColumn#11]
I use tabs in Java, and I have the tab-width set to 4 in my settings. Wrap to column doesn't respect this and wraps past the end of the right margin. Not sure if it's considering tabs as 1 character or two, though.

**Comment by abrookins** [comment]
Thank you, @emichael! I hope to look into this when I have time for another round of fixes.

**Comment by abrookins** [comment]
@emichael I'm still not sure what to do about tabs. Since tabs have a variable display width, couldn't you reflow a paragraph that works for your tab-width setting, only to have a coworker whose tab-width is different complain that the lines are over the margin for them? As a tab user, what would you most expect the plugin to do -- use your configured tab-width is?

**Comment by emichael** [comment]
Yes. Members of the same project should all be using an agreed upon tab-width, anyways. Besides, you're always going to have that problem (that people can use different tab-widths), and making the plugin respect the current configuration is strictly better than it assuming some set value.

**Comment by abrookins** [comment]
Ok, I'm convinced, and thank you again for taking the time to report. This is next up on my list.

**Comment by abrookins** [comment]
@emichael I made a Github release with my attempt to fix this issue: https://github.com/abrookins/WrapToColumn/releases/tag/1.2.0 in case you want to try it out before I release through Jetbrains.

**Comment by emichael** [comment]
Thanks! I don't have time to test it right now, unfortunately
