### ISSUE TITLE
The ClassNotFoundException thing is going to happen again in 2021.3

### ISSUE THREAD

**Issue by shoaniki** [abrookins/WrapToColumn#50]
Because versions > 1.4.0 are marked as only compatible up to 2021.2 :(

EAP beta exhibits the problem.

**Comment by abrookins** [comment]
Thank you, you're a life saver! I will attempt to release a fix this weekend.

**Comment by abrookins** [comment]
I'll need to download an EAP to test. I see that we use the `intellij { version = ... }` in build.gradle, which I thought only controlled which version of Intellij _built_ the plugin, and not what versions it supported. (Maybe the build version is related to the max version the plugin supports, though...)

I'll try removing that version specifier, which causes the gradle build to use the latest EAP snapshot (https://github.com/JetBrains/gradle-intellij-plugin#intellij-platform-properties).

The only other version-related stuff is `<idea-version since-build="141"/>`, and I don't know what version that actually is but it sounds like a minimum bound. 🤔

**Comment by abrookins** [comment]
Trying some recommendations on this page: https://plugins.jetbrains.com/docs/intellij/plugin-compatibility.html?from=jetbrains.org#exploring-module-and-plugin-apis

**Comment by abrookins** [comment]
Are you able to test this version with your EAP?

[WrapToColumn-1.8.0-SNAPSHOT.zip](https://github.com/abrookins/WrapToColumn/files/7491404/WrapToColumn-1.8.0-SNAPSHOT.zip)

**Comment by hoelzl** [comment]
I tried installing version 1.8.0-SNAPSHOT into PyCharm 2021.3 EAP and unfortunately the same error appears as for the previous snapshots: "Plugin is not compatible with the current version of the IDE, because it requires build 212.* or older but the current build is PY-213.5605.23"

**Comment by abrookins** [comment]
Ok, I just released 1.8.0 with what should be the fix for this. I've tested from a few different IDEs and versions, including the PyCharm EAP, and it seems to work!

Previous release:
<img width="878" alt="image" src="https://user-images.githubusercontent.com/97182/140664651-b1905603-fd30-4106-9ca7-a179467eb61f.png">

New release:
<img width="717" alt="image" src="https://user-images.githubusercontent.com/97182/140664673-16f47004-a3ac-450c-8dc3-8ab0b9e4192f.png">

**Comment by shoaniki** [comment]
Can confirm the update installed itself and is working perfectly in 2021.3 EAP, thank you!
